# Generated by Django 5.2.1 on 2025-08-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='nome',
            new_name='desenvolvedor',
        ),
        migrations.AddField(
            model_name='blog',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=models.TextField(),
        ),
    ]
