# Generated by Django 5.2.1 on 2025-07-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('status', models.CharField(choices=[('Concluída', 'Concluída'), ('Em andamento', 'Em andamento'), ('Pendente', 'Pendente')], default='Pendente', verbose_name='Status')),
                ('prazo', models.DateField(verbose_name='Prazo')),
            ],
        ),
    ]
